"""“m”

Revision ID: 30c139d90164
Revises: 
Create Date: 2019-12-08 17:24:58.069389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c139d90164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase', 'email_booking',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('purchase', 'email_customer',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase', 'email_customer',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('purchase', 'email_booking',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
