"""“m”

Revision ID: 949671c84820
Revises: 
Create Date: 2019-12-01 20:02:14.393379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949671c84820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('booking_agent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('airline',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('airport',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('customer',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('phone_num', sa.String(length=64), nullable=True),
    sa.Column('passport_num', sa.String(length=64), nullable=True),
    sa.Column('passport_expiration', sa.DateTime(), nullable=True),
    sa.Column('passport_country', sa.String(length=64), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('airline_staff',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('airline_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['airline_name'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('airplane',
    sa.Column('airline_name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_name'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('airline_name', 'id')
    )
    op.create_table('flight',
    sa.Column('airline_name', sa.String(length=64), nullable=False),
    sa.Column('flight_num', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('arrives', sa.String(length=64), nullable=True),
    sa.Column('departs', sa.String(length=64), nullable=True),
    sa.Column('airplane_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['airline_name', 'airplane_id'], ['airplane.airline_name', 'airplane.id'], ),
    sa.ForeignKeyConstraint(['arrives'], ['airport.name'], ),
    sa.ForeignKeyConstraint(['departs'], ['airport.name'], ),
    sa.PrimaryKeyConstraint('airline_name', 'flight_num', 'departure_time')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('airline_name', sa.String(length=64), nullable=True),
    sa.Column('flight_num', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_name', 'flight_num', 'departure_time'], ['flight.airline_name', 'flight.flight_num', 'flight.departure_time'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('purchase',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('email_booking', sa.String(length=64), nullable=True),
    sa.Column('email_customer', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('card_num', sa.Integer(), nullable=True),
    sa.Column('card_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_booking'], ['agent.email'], ),
    sa.ForeignKeyConstraint(['email_customer'], ['customer.email'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('ticket')
    op.drop_table('flight')
    op.drop_table('airplane')
    op.drop_table('airline_staff')
    op.drop_table('customer')
    op.drop_table('airport')
    op.drop_table('airline')
    op.drop_table('agent')
    # ### end Alembic commands ###
